# Welcome to Jekyll!

# Website settings
title: "Christopher Blake"
description: "Chris Blake's personal site."
keywords: "christopher,blake,SAS,consultant,adminsitrator"
# baseurl: "/"
# url: "https://cj13579.github.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Christopher Blake'
  first_name: 'Chris'
  last_name: 'Blake'
  email: 'cjb.blake@gmail.com'
  facebook_username: 'cj13579'
  github_username: 'cj13579'
  head_img: 'static/img/landing/Jack.jpg'
  desc: 'I do stuff.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# blog img path
# img_path: 'http://www.jack003.com/static/img/blog'

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
